import { Item } from "@shared/types/item.model";

const testItems: Item[] = [
    {
        id: "item1",
        name: "Grilled Chicken Skewer",
        description: "Juicy, marinated chicken grilled to perfection on a skewer.",
        active: true,
        price: 2.5,
        category: "Food",
        image_url: "https://example.com/images/grilled_chicken_skewer.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: 'parent',
    },
    {
        id: "item2",
        name: "Beef Taco",
        description: "Soft tortilla filled with seasoned beef, onions, and cilantro.",
        active: true,
        price: 3.0,
        category: "Food",
        image_url: "https://example.com/images/beef_taco.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: 'parent'
    },
    {
        id: "item3",
        name: "Vegetarian Burrito",
        description: "A large tortilla filled with beans, rice, vegetables, and cheese.",
        active: true,
        price: 4.0,
        category: "Food",
        image_url: "https://example.com/images/vegetarian_burrito.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: 'parent'
    },
    {
        id: "item4",
        name: "Fresh Lemonade",
        description: "Refreshing homemade lemonade with a hint of mint.",
        active: true,
        price: 1.5,
        category: "Beverages",
        image_url: "https://example.com/images/fresh_lemonade.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: 'parent'
    },
    {
        id: "item5",
        name: "Iced Coffee",
        description: "Chilled coffee with milk and sugar, perfect for a hot day.",
        active: true,
        price: 2.0,
        category: "Beverages",
        image_url: "https://example.com/images/iced_coffee.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: 'parent'
    },
    {
        id: "item6",
        name: "Nacho Chips",
        description: "Crispy nacho chips served with a side of cheese dip.",
        active: true,
        price: 2.0,
        category: "Snacks",
        image_url: "https://example.com/images/nacho_chips.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: 'parent'
    },
    {
        id: "item7",
        name: "Churros",
        description: "Deep-fried dough pastries coated in cinnamon sugar.",
        active: true,
        price: 2.5,
        category: "Desserts",
        image_url: "https://example.com/images/churros.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: 'parent'
    },
    {
        id: "item8",
        name: "Hot Sauce",
        description: "Spicy and flavorful hot sauce to add a kick to your meal.",
        active: true,
        price: 0.5,
        category: "Condiments",
        image_url: "https://example.com/images/hot_sauce.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: 'parent'
    },
    {
        id: "item20",
        name: "Fish Tacos",
        description: "Grilled fish with cabbage slaw and lime crema.",
        active: true,
        price: 3.5,
        category: "Food",
        image_url: "https://example.com/images/fish_tacos.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: 'parent',
    },
    {
        id: "item21",
        name: "Chicken Quesadilla",
        description: "Grilled chicken with melted cheese in a crispy tortilla.",
        active: true,
        price: 4.0,
        category: "Food",
        image_url: "https://example.com/images/chicken_quesadilla.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: 'parent',
    },
    {
        id: "item22",
        name: "Bean and Cheese Burrito",
        description: "Refried beans and melted cheese wrapped in a warm tortilla.",
        active: true,
        price: 3.0,
        category: "Food",
        image_url: "https://example.com/images/bean_cheese_burrito.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: 'parent',
    },
    // Additional Beverages
    {
        id: "item30",
        name: "Horchata",
        description: "Traditional rice and cinnamon drink.",
        active: true,
        price: 2.0,
        category: "Beverages",
        image_url: "https://example.com/images/horchata.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: 'parent',
    },
    {
        id: "item31",
        name: "Jamaica (Hibiscus Tea)",
        description: "Sweet and tart hibiscus iced tea.",
        active: true,
        price: 2.0,
        category: "Beverages",
        image_url: "https://example.com/images/jamaica.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: 'parent',
    },
    {
        id: "item32",
        name: "Mexican Coca-Cola",
        description: "Classic Coca-Cola made with real cane sugar.",
        active: true,
        price: 2.5,
        category: "Beverages",
        image_url: "https://example.com/images/mexican_coke.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: 'parent',
    },
    // Additional Snacks
    {
        id: "item40",
        name: "Elote (Mexican Street Corn)",
        description: "Grilled corn with mayo, cheese, chili powder, and lime.",
        active: true,
        price: 3.0,
        category: "Snacks",
        image_url: "https://example.com/images/elote.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: 'parent',
    },
    {
        id: "item41",
        name: "Chips and Dips Combo",
        description: "Tortilla chips with your choice of three dips.",
        active: true,
        price: 4.5,
        category: "Snacks",
        image_url: "https://example.com/images/chips_dips.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: 'parent',
    },
    // Additional Desserts
    {
        id: "item50",
        name: "Flan",
        description: "Creamy caramel custard dessert.",
        active: true,
        price: 3.0,
        category: "Desserts",
        image_url: "https://example.com/images/flan.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: 'parent',
    },
    {
        id: "item51",
        name: "Sopapillas",
        description: "Fried pastry puffs dusted with cinnamon sugar.",
        active: true,
        price: 2.5,
        category: "Desserts",
        image_url: "https://example.com/images/sopapillas.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: 'parent',
    },
];

export default testItems;
