import { ChildItem } from "@shared/types/item.model";

const testChildItems: ChildItem[] = [
    {
        id: "child1",
        name: "Cheese Dip",
        description: "A smooth, melted cheese dip with a hint of spice.",
        active: true,
        price: 1.0,
        category: "Snacks",
        image_url: "https://example.com/images/cheese_dip.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: "child",
    },
    {
        id: "child2",
        name: "Salsa Dip",
        description: "Fresh tomato salsa with a mild kick of spice.",
        active: true,
        price: 0.8,
        category: "Snacks",
        image_url: "https://example.com/images/salsa_dip.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: "child",
    },
    {
        id: "child3",
        name: "Guacamole",
        description: "Creamy avocado guacamole with lime and cilantro.",
        active: true,
        price: 1.2,
        category: "Snacks",
        image_url: "https://example.com/images/guacamole.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: "child",
    },
    {
        id: "child10",
        name: "Chipotle Mayo",
        description: "Smoky, spicy mayonnaise sauce.",
        active: true,
        price: 0.8,
        category: "Snacks",
        image_url: "https://example.com/images/chipotle_mayo.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: "child",
    },
    {
        id: "child11",
        name: "Bean Dip",
        description: "Warm refried beans with melted cheese.",
        active: true,
        price: 1.0,
        category: "Snacks",
        image_url: "https://example.com/images/bean_dip.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: "child",
    },
    {
        id: "child12",
        name: "Pico de Gallo",
        description: "Fresh chopped tomatoes, onions, and cilantro.",
        active: true,
        price: 0.8,
        category: "Snacks",
        image_url: "https://example.com/images/pico_de_gallo.jpg",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        company_id: "vendor_001",
        type: "child",
    },
];

export default testChildItems;
